CREATE TABLE "GCG_6157_VEND_MSTR_AUDIT" (
 "VENDOR_ID" CHAR(6),
 "FIELD_NAME" CHAR(50),
 "OLD_VALUE" LONGVARCHAR,
 "NEW_VALUE" LONGVARCHAR,
 "CHG_PGM" CHAR(8),
 "CHG_USER" CHAR(8),
 "CHG_DATE" DATE,
 "CHG_TIME" TIME );
CREATE INDEX "GCG_6157_IDX1" USING 0 ON "GCG_6157_VEND_MSTR_AUDIT" ( "VENDOR_ID" );
